# Generated by Django 3.1.3 on 2020-11-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTodos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todo_msg', models.CharField(max_length=256)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
